
Parameters:

  NotebookName:
    Type: String
    Default: PersonalizeDemoLab
    Description: Enter the name of the SageMaker notebook instance. Deafault is PersonalizeDemoLab.


Resources:

  # SageMaker Execution Role
  PersonalizeRoleForLab:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service: [sagemaker.amazonaws.com, personalize.amazonaws.com]
            Action: sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/service-role/AmazonPersonalizeFullAccess"
        - "arn:aws:iam::aws:policy/IAMFullAccess"

  # SageMaker notebook
  NotebookInstance:
    Type: "AWS::SageMaker::NotebookInstance"
    Properties:
      InstanceType: "ml.t3.medium"
      NotebookInstanceName: !Ref NotebookName
      RoleArn: !GetAtt PersonalizeRoleForLab.Arn
      DefaultCodeRepository: https://github.com/vavourak/bp-personalize-lab-2020.git
